# Generated by Django 4.1.2 on 2022-11-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(upload_to='product/video/'),
        ),
    ]
